### ISSUE TITLE
Скорость

### ISSUE THREAD

**Issue by hafelectronics** [GyverLibs/OVS#1]
Есть недочеты по библиотеке:
1. в цикле переборки используется переменная i типа int(2 байта), но считает максимум до 6и. может это исправляет компилятор, но все таки хорошо использовать восьмибитку на переборку.
2. Если АЦП использует 10 бит и повышаем до 16, то переменная "**_sum**" на 32 бита это все таки многовато. тут бы тоже перебрать программу.
3. программа **analogRead(pin)** сама по себе тоже долго выполняется. Неплохо было бы обойти механизм подготовки работы АЦП.

**Comment by GyverLibs** [comment]
1. Ерунда, там вопрос пары тактов МК. А цикл не по 6 значениям идёт, при повышении до 6 бит он идёт до 4096 как бы...
2. Тоже ерунда
3. Ну это уже совсем извините чушь))) Выполняется ровно столько, на сколько настроен предделитель АЦП, у avr скорость оцифровки можно настроить в регистре АЦП если это нужно. А библиотека универсальная, для любых Ардуино совместимых платформ, у всех реализация аналогрида - разная. Для полного кастома в библиотеке предусмотрен ручной режим, в котором можно закидывать полученные любым способом данные
